import { SpeciesConfig, SpeciesType } from "./types";

/**
 * Section 3: Species Configuration
 * Configures behavior per species without hardcoding individual classes.
 * Includes all required parameters:
 * movementSpeed, preferredEnvironment, food, groupSize, idleTime, wanderTime, wanderRadius, canPet, canFeed.
 */
export const SPECIES_CONFIGS: Record<SpeciesType, SpeciesConfig> = {
  cow: {
    species: "cow",
    entityType: "ANIMAL",
    name: "Cow",
    movementSpeed: 0.8,
    defaultSpeed: 0.8,
    preferredEnvironment: ["GRASSLAND", "VILLAGE"],
    preferredEnvironments: ["GRASSLAND", "VILLAGE"],
    food: "grass",
    groupSize: { min: 2, max: 4 },
    groupSizeMin: 2,
    groupSizeMax: 4,
    idleTime: { min: 4.0, max: 8.0 },
    idleDurationMin: 4.0,
    idleDurationMax: 8.0,
    wanderTime: { min: 3.0, max: 6.0 },
    wanderDurationMin: 3.0,
    wanderDurationMax: 6.0,
    wanderRadius: 4.5, // 3–7 tiles away (Section 10)
    eatingDuration: 5.0,
    hungerRate: 2.0,
    hungerThreshold: 55,
    canPet: true,
    canFeed: true,
    health: 100,

    shadowRadiusX: 13,
    shadowRadiusY: 5.5,
    spriteAsset: {
      sheetPath:
        "/Sunnyside_World_ASSET_PACK_V2.1/Sunnyside_World_Assets/Elements/Animals/spr_deco_cow_strip4.png",
      frameWidth: 32,
      frameHeight: 32,
      totalFrames: 4,
      frameSpeed: 0.22,
      drawWidth: 36,
      drawHeight: 36,
      originYOffset: 6,
    },
  },

  sheep: {
    species: "sheep",
    entityType: "ANIMAL",
    name: "Sheep",
    movementSpeed: 1.1,
    defaultSpeed: 1.1,
    preferredEnvironment: ["GRASSLAND"],
    preferredEnvironments: ["GRASSLAND"],
    food: "grass",
    groupSize: { min: 3, max: 6 },
    groupSizeMin: 3,
    groupSizeMax: 6,
    idleTime: { min: 3.0, max: 7.0 },
    idleDurationMin: 3.0,
    idleDurationMax: 7.0,
    wanderTime: { min: 2.5, max: 5.0 },
    wanderDurationMin: 2.5,
    wanderDurationMax: 5.0,
    wanderRadius: 5.0, // 3–7 tiles away
    eatingDuration: 4.5,
    hungerRate: 2.2,
    hungerThreshold: 50,
    canPet: true,
    canFeed: true,
    health: 80,
    shadowRadiusX: 11,
    shadowRadiusY: 5,
    spriteAsset: {
      sheetPath:
        "/Sunnyside_World_ASSET_PACK_V2.1/Sunnyside_World_Assets/Elements/Animals/spr_deco_sheep_01_strip4.png",
      frameWidth: 32,
      frameHeight: 32,
      totalFrames: 4,
      frameSpeed: 0.2,
      drawWidth: 32,
      drawHeight: 32,
      originYOffset: 5,
    },
  },

  rabbit: {
    species: "rabbit",
    entityType: "ANIMAL",
    name: "Rabbit",
    movementSpeed: 1.8, // nimble & quick
    defaultSpeed: 1.8,
    preferredEnvironment: ["GRASSLAND", "JUNGLE"],
    preferredEnvironments: ["GRASSLAND", "JUNGLE"],
    food: "grass",
    groupSize: { min: 2, max: 4 },
    groupSizeMin: 2,
    groupSizeMax: 4,
    idleTime: { min: 1.5, max: 4.0 },
    idleDurationMin: 1.5,
    idleDurationMax: 4.0,
    wanderTime: { min: 1.2, max: 2.5 },
    wanderDurationMin: 1.2,
    wanderDurationMax: 2.5,
    wanderRadius: 4.0, // 3–7 tiles away
    eatingDuration: 3.0,
    hungerRate: 3.2,
    hungerThreshold: 45,
    canPet: true,
    canFeed: true,
    health: 35,
    shadowRadiusX: 6,
    shadowRadiusY: 2.5,
    spriteAsset: {
      sheetPath:
        "/Sunnyside_World_ASSET_PACK_V2.1/Sunnyside_World_Assets/Elements/Animals/spr_deco_bird_01_strip4.png",
      frameWidth: 16,
      frameHeight: 16,
      totalFrames: 4,
      frameSpeed: 0.14,
      drawWidth: 20,
      drawHeight: 20,
      originYOffset: 3,
    },
  },

  chicken: {
    species: "chicken",
    entityType: "ANIMAL",
    name: "Chicken",
    movementSpeed: 1.3,
    defaultSpeed: 1.3,
    preferredEnvironment: ["VILLAGE", "GRASSLAND"],
    preferredEnvironments: ["VILLAGE", "GRASSLAND"],
    food: "seeds",
    groupSize: { min: 2, max: 5 },
    groupSizeMin: 2,
    groupSizeMax: 5,
    idleTime: { min: 1.5, max: 4.5 },
    idleDurationMin: 1.5,
    idleDurationMax: 4.5,
    wanderTime: { min: 1.0, max: 3.0 },
    wanderDurationMin: 1.0,
    wanderDurationMax: 3.0,
    wanderRadius: 3.5, // 3–7 tiles away
    eatingDuration: 3.0,
    hungerRate: 3.0,
    hungerThreshold: 40,
    canPet: true,
    canFeed: true,
    health: 40,
    shadowRadiusX: 6,
    shadowRadiusY: 2.5,
    spriteAsset: {
      sheetPath:
        "/Sunnyside_World_ASSET_PACK_V2.1/Sunnyside_World_Assets/Elements/Animals/spr_deco_chicken_01_strip4.png",
      frameWidth: 32,
      frameHeight: 32,
      totalFrames: 4,
      frameSpeed: 0.15,
      drawWidth: 26,
      drawHeight: 26,
      originYOffset: 4,
    },
  },

  deer: {
    species: "deer",
    entityType: "ANIMAL",
    name: "Deer",
    movementSpeed: 1.6,
    defaultSpeed: 1.6,
    preferredEnvironment: ["JUNGLE", "GRASSLAND"],
    preferredEnvironments: ["JUNGLE", "GRASSLAND"],
    food: "grass",
    groupSize: { min: 2, max: 4 },
    groupSizeMin: 2,
    groupSizeMax: 4,
    idleTime: { min: 3.0, max: 7.0 },
    idleDurationMin: 3.0,
    idleDurationMax: 7.0,
    wanderTime: { min: 2.0, max: 5.0 },
    wanderDurationMin: 2.0,
    wanderDurationMax: 5.0,
    wanderRadius: 6.0, // 3–7 tiles away
    eatingDuration: 4.0,
    hungerRate: 2.0,
    hungerThreshold: 55,
    canPet: true,
    canFeed: true,
    health: 90,
    shadowRadiusX: 12,
    shadowRadiusY: 5,
    spriteAsset: {
      sheetPath:
        "/Sunnyside_World_ASSET_PACK_V2.1/Sunnyside_World_Assets/Elements/Animals/spr_deco_sheep_01_strip4.png",
      frameWidth: 32,
      frameHeight: 32,
      totalFrames: 4,
      frameSpeed: 0.16,
      drawWidth: 34,
      drawHeight: 34,
      originYOffset: 5,
    },
  },

  pig: {
    species: "pig",
    entityType: "ANIMAL",
    name: "Pig",
    movementSpeed: 1.0,
    defaultSpeed: 1.0,
    preferredEnvironment: ["GRASSLAND", "VILLAGE"],
    preferredEnvironments: ["GRASSLAND", "VILLAGE"],
    food: "carrots",
    groupSize: { min: 2, max: 4 },
    groupSizeMin: 2,
    groupSizeMax: 4,
    idleTime: { min: 2.5, max: 6.0 },
    idleDurationMin: 2.5,
    idleDurationMax: 6.0,
    wanderTime: { min: 2.0, max: 4.5 },
    wanderDurationMin: 2.0,
    wanderDurationMax: 4.5,
    wanderRadius: 4.0, // 3–7 tiles away
    eatingDuration: 4.0,
    hungerRate: 2.5,
    hungerThreshold: 45,
    canPet: true,
    canFeed: true,
    health: 90,

    shadowRadiusX: 10,
    shadowRadiusY: 4.5,
    spriteAsset: {
      sheetPath:
        "/Sunnyside_World_ASSET_PACK_V2.1/Sunnyside_World_Assets/Elements/Animals/spr_deco_pig_01_strip4.png",
      frameWidth: 32,
      frameHeight: 32,
      totalFrames: 4,
      frameSpeed: 0.18,
      drawWidth: 32,
      drawHeight: 32,
      originYOffset: 5,
    },
  },

  duck: {
    species: "duck",
    entityType: "ANIMAL",
    name: "Duck",
    movementSpeed: 1.1,
    defaultSpeed: 1.1,
    preferredEnvironment: ["WATER"],
    preferredEnvironments: ["WATER"],
    food: "grain",
    groupSize: { min: 2, max: 5 },
    groupSizeMin: 2,
    groupSizeMax: 5,
    idleTime: { min: 2.0, max: 5.0 },
    idleDurationMin: 2.0,
    idleDurationMax: 5.0,
    wanderTime: { min: 2.0, max: 4.0 },
    wanderDurationMin: 2.0,
    wanderDurationMax: 4.0,
    wanderRadius: 3.5, // 3–7 tiles away
    eatingDuration: 3.5,
    hungerRate: 2.5,
    hungerThreshold: 50,
    canPet: true,
    canFeed: true,
    health: 50,
    isAquatic: true, // Swims in water ponds
    shadowRadiusX: 7,
    shadowRadiusY: 3.5,
    spriteAsset: {
      sheetPath:
        "/Sunnyside_World_ASSET_PACK_V2.1/Sunnyside_World_Assets/Elements/Animals/spr_deco_duck_01_strip4.png",
      frameWidth: 16,
      frameHeight: 16,
      totalFrames: 4,
      frameSpeed: 0.16,
      drawWidth: 24,
      drawHeight: 24,
      originYOffset: 3,
    },
  },

  villager: {
    species: "villager",
    entityType: "NPC",
    name: "Villager",
    movementSpeed: 1.2,
    defaultSpeed: 1.2,
    preferredEnvironment: ["VILLAGE"],
    preferredEnvironments: ["VILLAGE"],
    food: "none",
    groupSize: { min: 1, max: 2 },
    groupSizeMin: 1,
    groupSizeMax: 2,
    idleTime: { min: 3.0, max: 8.0 },
    idleDurationMin: 3.0,
    idleDurationMax: 8.0,
    wanderTime: { min: 3.0, max: 6.0 },
    wanderDurationMin: 3.0,
    wanderDurationMax: 6.0,
    wanderRadius: 5.0,
    eatingDuration: 0,
    hungerRate: 0,
    hungerThreshold: 100,
    canPet: false,
    canFeed: false,
    health: 100,
    shadowRadiusX: 11,
    shadowRadiusY: 5.2,
    spriteAsset: {
      sheetPath:
        "/Sunnyside_World_ASSET_PACK_V2.1/Sunnyside_World_Assets/Characters/Human/WALKING/base_walk_strip8.png",
      frameWidth: 20,
      frameHeight: 24,
      totalFrames: 8,
      frameSpeed: 0.11,
      drawWidth: 34,
      drawHeight: 38,
      originYOffset: 5,
      sourceCropX: 38,
      sourceCropY: 18,
      strideX: 96,
    },
  },

  player: {
    species: "player",
    entityType: "PLAYER",
    name: "Player",
    movementSpeed: 3.4,
    defaultSpeed: 3.4,
    preferredEnvironment: ["VILLAGE"],
    preferredEnvironments: ["VILLAGE"],
    food: "none",
    groupSize: { min: 1, max: 1 },
    groupSizeMin: 1,
    groupSizeMax: 1,
    idleTime: { min: 0, max: 0 },
    idleDurationMin: 0,
    idleDurationMax: 0,
    wanderTime: { min: 0, max: 0 },
    wanderDurationMin: 0,
    wanderDurationMax: 0,
    wanderRadius: 0,
    eatingDuration: 0,
    hungerRate: 0,
    hungerThreshold: 100,
    canPet: false,
    canFeed: false,
    health: 100,
    shadowRadiusX: 11,
    shadowRadiusY: 5.2,
    spriteAsset: {
      sheetPath:
        "/Sunnyside_World_ASSET_PACK_V2.1/Sunnyside_World_Assets/Characters/Human/WALKING/base_walk_strip8.png",
      frameWidth: 20,
      frameHeight: 24,
      totalFrames: 8,
      frameSpeed: 0.1,
      drawWidth: 34,
      drawHeight: 38,
      originYOffset: 5,
      sourceCropX: 38,
      sourceCropY: 18,
      strideX: 96,
    },
  },
};
